apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metacatalog.fullname" . }}
  labels:
    {{- include "metacatalog.labels" . | nindent 4 }}
data:
  spring.profiles.active: {{ .Values.application.springProfile | quote }}
  java.opts: {{ .Values.application.javaOpts | quote }}
  logging.level.root: {{ .Values.application.logging.level.root | quote }}
  logging.level.app: {{ .Values.application.logging.level.app | quote }}
