apiVersion: v1
kind: ConfigMap
metadata:
  name: metacatalog-config
  namespace: applications
  labels:
    app.kubernetes.io/name: metacatalog
    app.kubernetes.io/component: application
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  INGRESS_URL: "https://metacatalog.example.com"
  INGRESS_DESCRIPTION: "Metacatalog API (Ingress)"
  SPRINGDOC_API_DOCS_ENABLED: "true"