apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-metacatalog-daily-backup
  namespace: applications
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: metacatalog-db
  immediate: true
  method: barmanObjectStore