openapi: "3.1.0"
info:
  version: 1.0.0
  title: Meta Catalog Manager API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
tags:
  - name: Meta Catalog Manager
paths:
  /metacatalog/v1/trait:
    post:
      tags:
        - Meta Catalog Manager
      summary: Create a user-defined trait
      operationId: createTrait
      requestBody:
        description: A Trait spec
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trait'
        required: true
      responses:
        204:
          description: Trait created
        400:
          description: Invalid input; details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem, details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/trait/{name}:
    get:
      tags:
        - Meta Catalog Manager
      summary: Get a trait by name
      operationId: getTrait
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Trait name
      responses:
        200:
          description: If successful, return a Trait object
          content:
             application/json:
               schema:
                 $ref: '#/components/schemas/Trait'
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
    delete:
      tags:
        - Meta Catalog Manager
      summary: Delete a trait by name
      operationId: deleteTrait
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Trait name
      responses:
        204:
          description: Trait deleted
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
    head:
      tags:
        - Meta Catalog Manager
      summary: Check if a trait exists by name
      operationId: traitExists
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Trait name
      responses:
        200:
          description: Trait exists
        404:
          description: Trait does not exist
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
components:
  schemas:
    Trait:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        schema:
          type: string
        inheritsFrom:
          type: string
    ValidationError:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    SystemError:
      required:
        - error
      type: object
      properties:
        error:
          type: string
