openapi: "3.1.0"
info:
  version: 1.0.0
  title: Meta Catalog Manager API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
tags:
  - name: Meta Catalog Manager
paths:
  /metacatalog/v1/trait:
    post:
      tags:
        - Meta Catalog Manager
      summary: Create a user-defined trait
      operationId: createTrait
      requestBody:
        description: A Trait spec
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trait'
        required: true
      responses:
        204:
          description: Trait created
        400:
          description: Invalid input; details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem, details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/trait/{name}:
    get:
      tags:
        - Meta Catalog Manager
      summary: Get a trait by name
      operationId: getTrait
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Trait name
      responses:
        200:
          description: If successful, return a Trait object
          content:
             application/json:
               schema:
                 $ref: '#/components/schemas/Trait'
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
    delete:
      tags:
        - Meta Catalog Manager
      summary: Delete a trait by name
      operationId: deleteTrait
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Trait name
      responses:
        204:
          description: Trait deleted
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
    head:
      tags:
        - Meta Catalog Manager
      summary: Check if a trait exists by name
      operationId: existsTrait
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Trait name
      responses:
        200:
          description: Trait exists
        404:
          description: Trait does not exist
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/trait/link:
    post:
      tags:
        - Meta Catalog Manager
      summary: Create a link between two traits by a relation
      operationId: linkTrait
      requestBody:
        description: A Link Trait spec
        content:
          application/json:
            schema:
              required:
                - sourceTrait
                - relationshipTypeName
                - targetTrait
              type: object
              properties:
                sourceTrait:
                  type: string
                relationshipTypeName:
                  type: string
                targetTrait:
                  type: string
        required: true
      responses:
        204:
          description: Trait link created
        400:
          description: Invalid input; details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem, details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/trait/link/{sourceTrait}/{relationshipTypeName}/{targetTrait}:
    delete:
      tags:
        - Meta Catalog Manager
      summary: Delete a link between two traits by a relation
      operationId: unlinkTrait
      parameters:
        - in: path
          name: sourceTrait
          required: true
          schema:
            type: string
            description: Source Trait name
        - in: path
          name: relationshipTypeName
          required: true
          schema:
            type: string
            description: A relationship type name
        - in: path
          name: targetTrait
          required: true
          schema:
            type: string
            description: Target Trait name
      responses:
        204:
          description: Link deleted
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
    head:
      tags:
        - Meta Catalog Manager
      summary: Check if a link exists between two traits by a relation
      operationId: existsLinkTrait
      parameters:
        - in: path
          name: sourceTrait
          required: true
          schema:
            type: string
            description: Source Trait name
        - in: path
          name: relationshipTypeName
          required: true
          schema:
            type: string
            description: A relationship type name
        - in: path
          name: targetTrait
          required: true
          schema:
            type: string
            description: Target Trait name
      responses:
        200:
          description: Link exists
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/trait/link/{sourceTrait}/{relationshipTypeName}:
    get:
      tags:
        - Meta Catalog Manager
      summary: Get the traits linked to a trait by a relation
      operationId: linkedTrait
      parameters:
        - in: path
          name: sourceTrait
          required: true
          schema:
            type: string
            description: Source Trait name
        - in: path
          name: relationshipTypeName
          required: true
          schema:
            type: string
            description: Relationship Type Name
      responses:
        200:
          description: If successful, return a list of linked traits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trait'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/type:
    post:
      tags:
        - Meta Catalog Manager
      summary: Create a user-defined type
      operationId: createEntityType
      requestBody:
        description: An EntityType spec
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityType'
        required: true
      responses:
        204:
          description: EntityType created
        400:
          description: Invalid input; details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        500:
          description: System problem, details of the error are provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemError'
  /metacatalog/v1/type/{name}:
    get:
      tags:
        - Meta Catalog Manager
      summary: Get a user-defined type by name
      operationId: getEntityType
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: EntityType name
      responses:
        200:
          description: If successful, return an EntityType object
          content:
             application/json:
               schema:
                 $ref: '#/components/schemas/EntityType'
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
    delete:
      tags:
        - Meta Catalog Manager
      summary: Delete a user-defined type by name
      operationId: deleteEntityType
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: EntityType name
      responses:
        204:
          description: Type deleted
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
    head:
      tags:
        - Meta Catalog Manager
      summary: Check if a user-defined type exists by name
      operationId: existsEntityType
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: EntityType name
      responses:
        200:
          description: EntityType exists
        404:
          description: EntityType does not exist
        400:
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ValidationError'
        500:
           description: System problem
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/SystemError'
components:
  schemas:
    Trait:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        schema:
          type: string
        inheritsFrom:
          type: string
    EntityType:
      required:
        - name
        - schema
      type: object
      properties:
        name:
          type: string
        schema:
          type: string
        traits:
          type: array
          items:
            type: string
        inheritsFrom:
          type: string
    ValidationError:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    SystemError:
      required:
        - error
      type: object
      properties:
        error:
          type: string
