spring:
  config:
    activate:
      on-profile: "default"
  datasource:
    url: jdbc:postgresql://localhost:5432/metacatalog
    username: metacatalog
    password: metacatalog
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      # Use 'none' since Flyway manages the schema; validation happens at runtime through queries
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api/interface-specification.yaml
  api-docs:
    path: /api-docs
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: beans, caches, health, info, flyway, metrics, env, configprops, loggers
logging:
  level:
    root: ERROR                                # General logging level for the application
    org.springframework.data.jpa.repository: ERROR  # Log JPA repository method calls
    org.hibernate.SQL: ERROR                   # Log SQL statements executed by Hibernate
    org.hibernate.type.descriptor.sql: ERROR   # Log SQL parameter binding
application:
  config:
    automaticEntitiesMapping: true
    updateMappedEntitiesSchedulingInterval: 1s
    entityLifeCycleEventCleanupSchedulingInterval: 1s
    entityPathResolutionMaxAttempts: 3